module.exports = [
    'LOGIN',
    'LOGIN_SUCCESS',
    'CLIENTS_UPDATE',
    'INVITATION_SEND',
    'INVITATION_RECEIVED',
    'INVITATION_CANCEL',
    'INVITATION_CANCELED',
    'INVITATION_ACCEPT',
    'INVITATION_ACCEPTED',
    'INVITATION_DECLINE',
    'INVITATION_DECLINED',
    'READER_PAGE',
    'READER_PAGED',
    'READER_LEAVE',
    'READER_LEFT',
    'POINTER_ENABLE',
    'POINTER_DISABLE',
    'POINTER_MOVE',
    'POINTER_ENABLED',
    'POINTER_DISABLED',
    'POINTER_MOVED'
].reduce((acc, val) => {
    acc[val] = val;
    return acc;
}, {});
